name: Code Style

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ts:
    name: TS Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm install
      - name: Run prettier
        run: |
          shopt -s globstar
          npx prettier -w src/**/*.ts
      - run: echo "::add-matcher::.github/diff.json"
      - name: Show diff
        run: |
          git checkout -- package-lock.json
          git diff --exit-code
